networks:
  ecomnet:
    driver: bridge
  
services:
  bestbags-backend: 
    container_name: bestbags-backend
    build: ./bestbags-nodejs-ecommerce-master
    networks:
      - ecomnet
    ports:
      - '5002:5002'
    environment:
      MONGO_URI: "mongodb://root:root@mongo:27017/"
      SESSION_SECRET: "uggabugga"
    volumes:
      - ./data:/home/node/data/db

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - ecomnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: database

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    networks:
      - ecomnet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus:/etc/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
      
